server:
  port: 8083

spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/employee-gateway/**
          filters:
           - RewritePath=/employee-gateway/(?<path>.*), /$\{path}
         

eureka:
  instance:
   hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


# Actuator (visualize the circuit-breaker state-changes)
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always